services:
  - type: web
    name: backend-python
    env: python
    rootDir: backend-python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port $PORT
      python -m spacy download en_core_web_sm

    plan: free
    autoDeploy: true
    envVars:
      - key: GROQ_API_KEY
        sync: false 